language: node_js

node_js:
- 4.1.1

env:
  global:
    secure: 87oi8gunps3N9u7Fi68argt7lc11HIobsGoypYuE6Vv/d6X9U4ZPTgfheJjInyqh+C1MSLDOe8IgwCpSPWu1ubAK0ZsiMJaLwz/5hKl8NCOFrwsA+y+ZpZzy+9fBENUOAtML+0oItdBxA1KNQHRNjRcX/fMn12pmz87g6E7oGdxcfOPyFWnwCvAWXuSluSh/9wEFRV3LsXB7ts4NhMI1Jshm7L54/loBW/E8JZulzBaEf2zlX010P1nCpUNn5p+eQotqhIpvD8hhCc9/Gk6kD0YyIw3BKvHfId37fK1Fic2nPLKgGlrqgkYnjbPS5El06adcPIRvY9KMYMBkHUkglpCNxVMzWgcP8sKP3k3hZyn2iuUFvw2T7Gej2o9ZO+vYL6Ch2/EZbTCfLiT5TYbhQk5H3HhTuBOVRRq/pfoLN4yZqo/h1z61dad6SEVFuP7qwEj3MJc+Ol8PfMTL2jmGuwsOedCT5pgEEXG0MvR65fPoshMW3HVaMEYHpz8XbAbp0oGOFfgrzD2apXBRj7chUmX1J5eZ8cwCl3Dil+1jhSogd2TdEnZppMxstIyi79ptoxDJZNbn/qD90POMQJG0AQ9/yakiCzcr2d9RsUH6KMFeSSlgcp0jG2Q8FCORLLtMD28V+ZIgeRvXmDgKwyhR4giO7rGq+RkqMEGr4rWk0NM=

install:
- npm install

script:
- npm test

after_success:
- npm run build
- bash scripts/deploy.bash
